{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15211712-29ff-4b91-8955-b17fd3a82b47",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import pickle\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "\n",
    "# --- PAGE CONFIGURATION ---\n",
    "st.set_page_config(page_title=\"AgroIntel Pro Enterprise\", layout=\"wide\", page_icon=\"🚜\")\n",
    "\n",
    "# Custom CSS to mimic the \"Mission Control\" look\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .main { background-color: #f8fafc; }\n",
    "    .stMetric { background-color: #ffffff; padding: 20px; border-radius: 15px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }\n",
    "    </style>\n",
    "    \"\"\", unsafe_base_with_markup=True)\n",
    "\n",
    "# --- LOAD MODELS & ASSETS ---\n",
    "@st.cache_resource\n",
    "def load_assets():\n",
    "    crop_model = pickle.load(open('crop_recommender.pkl', 'rb'))\n",
    "    irr_model = pickle.load(open('irrigation_model.pkl', 'rb'))\n",
    "    iot_model = pickle.load(open('iot_model.pkl', 'rb'))\n",
    "    encoders = pickle.load(open('encoders.pkl', 'rb'))\n",
    "    metadata = pickle.load(open('metadata.pkl', 'rb'))\n",
    "    return crop_model, irr_model, iot_model, encoders, metadata\n",
    "\n",
    "try:\n",
    "    crop_model, irr_model, iot_model, encoders, metadata = load_assets()\n",
    "except FileNotFoundError:\n",
    "    st.error(\"Model files not found. Please run your training script first!\")\n",
    "    st.stop()\n",
    "\n",
    "# --- SIDEBAR: CONTROL CENTER ---\n",
    "st.sidebar.title(\"🎛️ Control Center\")\n",
    "st.sidebar.markdown(\"---\")\n",
    "\n",
    "with st.sidebar.expander(\"Soil Nutrients (N-P-K)\", expanded=True):\n",
    "    n = st.number_input(\"Nitrogen (N)\", value=90)\n",
    "    p = st.number_input(\"Phosphorus (P)\", value=40)\n",
    "    k = st.number_input(\"Potassium (K)\", value=40)\n",
    "\n",
    "with st.sidebar.expander(\"Climate Telemetry\", expanded=True):\n",
    "    temp = st.slider(\"Temperature °C\", 10, 50, 30)\n",
    "    hum = st.slider(\"Humidity %\", 10, 100, 80)\n",
    "    ph = st.number_input(\"Soil pH\", 0.0, 14.0, 6.5)\n",
    "    rain = st.number_input(\"Rainfall mm\", value=20)\n",
    "\n",
    "soil_type = st.sidebar.selectbox(\"Soil Classification\", metadata['soils'])\n",
    "crop_selection = st.sidebar.selectbox(\"Target Configuration\", [\"Auto Prediction\"] + metadata['crops'])\n",
    "\n",
    "hw_link = st.sidebar.checkbox(\"Bridge IoT Protocol\")\n",
    "\n",
    "# --- MAIN DASHBOARD ---\n",
    "st.title(\"🚜 AgroIntel | Tactical Intelligence Dashboard\")\n",
    "st.markdown(\"Real-time predictive telemetry and resource optimization.\")\n",
    "\n",
    "if st.sidebar.button(\"DEPLOY ML ENGINE\", type=\"primary\", use_container_width=True):\n",
    "    # 1. Prediction Logic\n",
    "    c_feat = [[n, p, k, temp, hum, ph, rain]]\n",
    "    predicted_crop = crop_model.predict(c_feat)[0]\n",
    "    final_crop = predicted_crop if crop_selection == \"Auto Prediction\" else crop_selection\n",
    "    \n",
    "    # 2. Crop-Aware Operational Strategy\n",
    "    high_tech = ['rice', 'papaya', 'coconut', 'jute', 'coffee']\n",
    "    if final_crop.lower() in high_tech:\n",
    "        it, im, s = 'Pressurized', ('Drip' if temp > 30 else 'Sprinkler'), ('Summer' if temp > 30 else 'Monsoon')\n",
    "    else:\n",
    "        it, im, s = ('Surface' if rain > 20 else 'Sub-Surface'), ('Furrow' if temp > 25 else 'Manual'), ('Winter' if temp < 25 else 'Monsoon')\n",
    "\n",
    "    # 3. Irrigation Need Prediction\n",
    "    feat = [[\n",
    "        encoders['Soil_Type'].transform([soil_type])[0],\n",
    "        encoders['Crop_Type'].transform([final_crop])[0],\n",
    "        temp, hum, rain,\n",
    "        encoders['Season'].transform([s])[0],\n",
    "        encoders['Irr_Type'].transform([it])[0],\n",
    "        encoders['Irr_Method'].transform([im])[0]\n",
    "    ]]\n",
    "    \n",
    "    irr_idx = irr_model.predict(feat)[0]\n",
    "    status = encoders['Irrigation_Need'].inverse_transform([irr_idx])[0]\n",
    "    runtime = 45 if status == \"High\" else (25 if status == \"Medium\" else 10)\n",
    "\n",
    "    # --- TOP ROW: ANALYTICS ---\n",
    "    m1, m2, m3 = st.columns(3)\n",
    "    m1.metric(\"Recommended Crop\", final_crop.capitalize(), \"Optimal Match\")\n",
    "    m2.metric(\"Water Demand\", status, delta_color=\"inverse\")\n",
    "    m3.metric(\"System Runtime\", f\"{runtime} Mins\")\n",
    "\n",
    "    # --- MIDDLE ROW: STRATEGY MATRIX ---\n",
    "    st.markdown(\"### 📊 Tactical Strategy Profile\")\n",
    "    s1, s2, s3 = st.columns(3)\n",
    "    s1.info(f\"**Season**\\n\\n{s}\")\n",
    "    s2.info(f\"**System Type**\\n\\n{it}\")\n",
    "    s3.info(f\"**Method**\\n\\n{im}\")\n",
    "\n",
    "    # --- BOTTOM ROW: IOT NODES ---\n",
    "    if hw_link:\n",
    "        st.markdown(\"### 📡 IoT Node Actuation Array\")\n",
    "        valves = iot_model.predict([[np.random.uniform(2, 18) for _ in range(20)]])[0]\n",
    "        \n",
    "        n1, n2, n3, n4 = st.columns(4)\n",
    "        sectors = [n1, n2, n3, n4]\n",
    "        labels = [\"Alpha\", \"Beta\", \"Gamma\", \"Delta\"]\n",
    "        \n",
    "        for i, col in enumerate(sectors):\n",
    "            state = \"ACTIVE\" if valves[i] else \"IDLE\"\n",
    "            color = \"green\" if valves[i] else \"gray\"\n",
    "            col.markdown(f\"\"\"\n",
    "                <div style=\"text-align:center; padding:20px; border-radius:10px; border:2px solid {color}; background-color:white;\">\n",
    "                    <small>NODE {labels[i]}</small><br>\n",
    "                    <strong style=\"color:{color};\">{state}</strong>\n",
    "                </div>\n",
    "            \"\"\", unsafe_base_with_markup=True)\n",
    "else:\n",
    "    st.info(\"👈 Complete the environmental matrix in the sidebar and click 'Deploy Engine'.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
